// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"github.com/swaggo/swag"
	docsapp "dodevops-api/docs/app"
	docscmdb "dodevops-api/docs/cmdb"
	docsconfigcenter "dodevops-api/docs/configcenter"
	docsdashboard "dodevops-api/docs/dashboard"
	docsk8s "dodevops-api/docs/k8s"
	docsmonitor "dodevops-api/docs/monitor"
	docssystem "dodevops-api/docs/system"
	docstask "dodevops-api/docs/task"
	docstool "dodevops-api/docs/tool"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {` + docscmdb.CmdbPaths + "," + docsconfigcenter.ConfigcenterPaths + "," + docsdashboard.DashboardPaths + "," + docsk8s.K8sPaths + "," + docsmonitor.MonitorPaths + "," + docssystem.SystemPaths + "," + docstask.TaskPaths + "," + docstool.ToolPaths + `},
    "definitions": {` + docsapp.AppDefinitions + "," + docscmdb.CmdbDefinitions + "," + docsconfigcenter.ConfigcenterDefinitions + "," + docsdashboard.DashboardDefinitions + "," + docsk8s.K8sDefinitions + "," + docsmonitor.MonitorDefinitions + "," + docssystem.SystemDefinitions + "," + docstask.TaskDefinitions + "," + docstool.ToolDefinitions + `},
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }                                                                                           
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "devops运维管理系统",
	Description:      "devops运维管理系统API接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
